#!/bin/sh

. /usr/share/live-guest/functions
source_parts /etc/live-guest.d

action=$1

if [ "$action" = "mount" ] ; then
    oldid="user"
    newid="${USER}"
elif [ "$action" = "unmount" ] ; then
    oldid="${USER}"
    newid="user"
else
    exit 1
fi

sed -i -r "s/^userId([0-9]+)=${oldid}$/userId\1=${newid}/" \
	/home/${USER}/.kde/share/config/ksmserverrc

sed -i "s/home\/${oldid}/home\/${newid}/" \
	/home/${USER}/.kde/share/apps/kfileplaces/bookmarks.xml
