#!/bin/sh

. /usr/share/live-guest/functions
source_parts /etc/live-guest.d

action=$1

if [ "$action" = "mount" ] ; then
    oldid="user"
    newid="${USER}"
elif [ "$action" = "unmount" ] ; then
    oldid="${USER}"
    newid="user"
else
    exit 1
fi

sed_if_exists /home/${USER}/.shutter/settings.xml \
    "s|home/${oldid}|home/${newid}|"

