#!/bin/sh 

set -e

. /etc/live-guest.conf
. /usr/share/live-guest/functions

mkdir_if_not() {
  [ -d $1 ] || mkdir -p $1
}

# Check if a user session is running, exit if someone is logged in
if ck-list-sessions | grep -q Session ; then
    log notice "A user session is running, exiting."
    exit 0
fi

# Double check if we really have a disk, only disks
# should trigger the udev rule.
if [ "$DEVTYPE" != "disk" ] ; then
    log warn "Not a disk, exiting."
    exit 0
fi

# check lock file
if [ -f ${LOCKFILE} ] ; then
  LOCKDEV=$(cat ${LOCKFILE})

  # exit if our device is not the locked device and the locked
  # device still exists
  if [ "${LOCKDEV}" != "${DEVNAME}" -a -b ${LOCKDEV} ] ; then
      log notice "Another Debian Live guest system is already mounted."
      exit 0
  fi
fi

# Lock the device
echo ${DEVNAME} > ${LOCKFILE}

roopt="rr"
rofsstring=""
PARTITIONS=$(ls $DEVNAME?)
for p in ${PARTITIONS} ; do
  log debug "Checking partition: ${p}."

  # check if the partition is already mounted
  grep -q ${p} /proc/mounts && log debug "Partition ${p} already mounted." && continue
 
  # check for COW partition
  LABEL=$(blkid -o value -s LABEL ${p})
  log debug "Partition $p, Label: $LABEL"
  if [ "$LABEL" = "live-rw" ] ; then
     mkdir_if_not ${MOUNT_COW_DIR}
     mount ${p} ${MOUNT_COW_DIR}
     log notice "Mounted COW partition ${p} on ${COW_MOUNT_DIR}"
     continue
  fi

  # try to mount volume
  MOUNT_DIR="${MOUNT_PARTITIONS_DIR}/$(basename ${p})"
  mkdir_if_not ${MOUNT_DIR}
  mount ${p} ${MOUNT_DIR}
  log notice "Mounted partition ${p} on ${MOUNT_DIR}, now scanning for live filesystems."
  
  # check for live directory
  image_string=""
  if [ -d ${MOUNT_DIR}/live ] ; then
    # scan for filesystem images
    for FILESYSTEM in squashfs ext2 ext3 ext4 xfs jffs2 ; do
      for IMAGE in "${MOUNT_DIR}/live"/*."${FILESYSTEM}" ; do
        if [ -e "${IMAGE}" ] ; then
          image_string="${image_string} ${IMAGE}"
        fi
      done
    done

    if [ -n "${image_string}" ] ; then
      # mount filesystem images
      for image in ${image_string} ; do
        imagename=$(basename "${image}")
        MOUNT_IMAGE_DIR="${MOUNT_BASE_DIR}/${imagename}"
        mkdir_if_not ${MOUNT_IMAGE_DIR}
        mount -o loop,ro,noatime ${image} ${MOUNT_IMAGE_DIR}
        log notice "Mounted live filesystem image ${image} on ${MOUNT_IMAGE_DIR}."
        rofsstring="${MOUNT_IMAGE_DIR}=${roopt}:${rofsstring}"
      done
      continue
    fi
  fi

  # nothing interesting here, unmount
  umount ${p} && rmdir ${MOUNT_DIR}
  log notice "Unmounting partition ${p}. No live filesystems or COW partitions found."

done

# create root mount point
mkdir_if_not ${MOUNT_ROOT_DIR}

# Assemble aufs stacked filesystem
mount -t ${UNIONTYPE} -o noatime,noxino,dirs=${MOUNT_COW_DIR}=rw:${rofsstring%:} ${UNIONTYPE} "${MOUNT_ROOT_DIR}"
log notice "Assembled Debian Live union filesystem on ${MOUNT_ROOT_DIR}"

# create guest user if it does not yet exist
getent passwd ${USER} > /dev/null || adduser --gecos "Guest Live user" --no-create-home --disabled-login ${USER} && log debug "Created Guest Live user."

# Add user the default groups, get groups from debconf database
for group in $(echo "GET passwd/user-default-groups" | debconf-communicate | cut -c3-); do
  adduser "$USER" $group || true
  log debug "Added Guest Live user default groups."
done

# create and chown home directory
[ -d /home/${USER} ] || mkdir /home/${USER}
chown ${USER}:${USER} /home/${USER}

# copy password from guest stick
PW=$(egrep ^user: ${MOUNT_ROOT_DIR}/etc/shadow | cut -f 2 -d :)
usermod --password="$PW" ${USER}

# copy gecos from guest stick
GECOS=$(egrep ^user: ${MOUNT_ROOT_DIR}/etc/passwd | cut -f 5 -d : | cut -f 1 -d ,)
chfn -f "${GECOS} (Guest)" ${USER}

# bind mount to home directory
bindfs --map=user/${USER}:@user/@${USER} ${MOUNT_ROOT_DIR}/home/user /home/${USER}

# kill display manager greeter to show the new user
notify_dm

log notice "Finished mounting guest Debian Live system."