#!/bin/sh 

set -e

. /usr/share/live-guest/functions
source_parts /etc/live-guest.d

start_log

# check if called from pam_script or from udev
if [ -n "${PAM_USER}" ] ; then
  MODE="pam_script"
  log info "called from pam_script"
elif [ -n "${DEVNAME}" ] ; then
  MODE="udev"
  log info "called from udev rule"
else
  log error "Unknown calling mode."
  exit 1
fi

# check if called for a disk in udev mode
if [ "${MODE}" = "udev" ] && [ "${DEVTYPE}" != "disk" ] ; then
  log warn "Not a disk, exiting."
  exit 1
fi

# check lock file and read device node
if [ ! -r ${LOCKFILE} ] ; then 
    log info "Lockfile ${LOCKFILE} unreadable or does not exist, probably no live guest device mounted. Ignoring."
    exit 0
fi

LOCKDEV=$(cat ${LOCKFILE})

# exit if not called for the disk mounted by live-guest
if [ "${MODE}" = "udev" -a "${LOCKDEV}" != "${DEVNAME}" ] ; then
    log info "disk not mounted by live-guest, ignoring."
    exit 0
fi

# check if the user logging out is the live-guest user
if [ "${MODE}" = "pam_script" -a "${PAM_USER}" != "${USER}" ] ; then
    log info "${PAM_USER} is not the live guest user. Not unmounting live guest system."
    exit 0
fi

# run custom scripts
log info "Running custom scripts."
for dir in /usr/share/live-guest/unmount.d /usr/local/share/live-guest/unmount.d ; do
    [ -d ${dir} ] && run-parts --arg="unmount" ${dir}  2>&1 | logger -t live-guest -p user.notice
done

log notice "Unmounting guest Debian Live system from ${LOCKDEV}."

# unmount fuse bindfs mounted home dir
umount_and_remove /home/${USER}

# unmount aufs
umount_and_remove ${MOUNT_ROOT_DIR}

# unmount individual filesystems
for d in ${MOUNT_BASE_DIR}/* ; do

  # skip root, cow and partitions directories, should already be unmounted 
  # or will be unmounted later
  if [ "$d" = "${MOUNT_ROOT_DIR}" -o "$d" = "${MOUNT_COW_DIR}" -o "$d" = "${MOUNT_PARTITIONS_DIR}" ] ; then
    continue
  fi

  # unmount filesystem and remove mountpoint
  umount_and_remove  $d
done

# unmount partitions
for d in ${MOUNT_PARTITIONS_DIR}/* ; do 
  umount_and_remove $d
done

# unmount cow partition
umount_and_remove ${MOUNT_COW_DIR}

# check for other partitions that might be mounted, try to unmount them
for d in $(cat /proc/mounts | grep "^${LOCKDEV}" | cut -f 1 -d " ") ; do
  umount $d
done

rm -f ${LOCKFILE}
log notice "Unmounting guest Debian Live system on ${LOCKDEV} done."

remove_user

log info "Finished unmount Live guest device."