#!/bin/sh 

set -e

. /etc/live-guest.conf
. /usr/share/live-guest/functions

umount_and_remove() {
  if umount ${UNMOUNT_OPTS} $1 ; then
    rmdir $1
  else
    log warn "Unable to unmount $1"
  fi
}

# check if called from pam_script or from udev
if [ -n "${PAM_USER}" ] ; then
  MODE="pam_script"
  log info "called from pam_script"
elif [ -n "${DEVNAME}" ] ; then
  MODE="udev"
  log info "called from udev rule"
else
  log error "Unknown calling mode."
  exit 1
fi

# check if called for a disk in udev mode
if [ "${MODE}" = "udev" ] && [ "${DEVTYPE}" != "disk" ] ; then
  log warn "Not a disk, exiting."
  exit 1
fi

# check lock file and read device node
if [ ! -r ${LOCKFILE} ] ; then 
    log info "Lockfile ${LOCKFILE} unreadable or does not exist, probably no live guest device mounted. Ignoring."
    exit 0
fi

LOCKDEV=$(cat ${LOCKFILE})

# exit if not called for the disk mounted by live-guest
if [ "${MODE}" = "udev" -a "${LOCKDEV}" != "${DEVNAME}" ] ; then
    log info "disk not mounted by live-guest, ignoring."
    exit 0
fi

# check if the user logging out is the live-guest user
if [ "${MODE}" = "pam_script" -a "${PAM_USER}" != "${USER}" ] ; then
    log info "${PAM_USER} is not the live guest user. Not unmounting live guest system."
    exit 0
fi

log notice "Unmounting guest Debian Live system from ${LOCKDEV}."

# unmount fuse bindfs mounted home dir
umount_and_remove /home/${USER}

# unmount aufs
umount_and_remove ${MOUNT_ROOT_DIR}

# unmount individual filesystems
for d in ${MOUNT_BASE_DIR}/* ; do

  # skip root, cow and partitions directories, should already be unmounted 
  # or will be unmounted later
  if [ "$d" = "${MOUNT_ROOT_DIR}" -o "$d" = "${MOUNT_COW_DIR}" -o "$d" = "${MOUNT_PARTITIONS_DIR}" ] ; then
    continue
  fi

  # unmount filesystem and remove mountpoint
  umount_and_remove  $d
done

# unmount partitions
for d in ${MOUNT_PARTITIONS_DIR}/* ; do 
  umount_and_remove $d
done

# unmount cow partition
umount_and_remove ${MOUNT_COW_DIR}

# eject usb stick and remove lockfile
[ "${MODE}" = "pam_script" ] && eject ${LOCKDEV} && true
rm -f ${LOCKFILE}
log notice "Unmounting guest Debian Live system on ${LOCKDEV} done."

# remove user
# this is done manually because userdel checks if 
# the user is still logged in. There is a -f option to
# override this but it additionally forces other things 
# (like removing the home directory) which are too dangerous
if getent passwd ${USER} > /dev/null ; then
  for f in /etc/passwd /etc/shadow ; do
    sed --expression="/^${USER}:/ {d}" --in-place=- $f
  done
  for f in /etc/group /etc/gshadow ; do
    sed --regexp-extended --expression="{/^${USER}:/ d}; {/^[a-z0-9-]+:(x|\\!|\*):([0-9]+|):[a-z0-9,-]*${USER}/ s/,?${USER}//}" --in-place=- $f
  done
  log notice "Removed guest Debian Live user ${USER}."
fi

# notify display manager
notify_dm

log info "Finished unmount Live guest device."